services:
  aprsc:
    image: ghcr.io/loorisr/aprsc-docker:latest
    #build: .
    container_name: aprsc
    user: "aprsc"
    read_only: true
    cap_drop:
      - ALL
    volumes:
      - ./aprsc/aprsc.conf:/opt/aprsc/etc/aprsc.conf:ro
      - ./aprsc/data:/opt/aprsc/data
    ports:
      #- 8080:8080 # UDP submit
      #- 10152:10152 # Full feed
      #- 14501:14501 # Status page HTTP 
      - 14580:14580 # Client-Defined Filters
    restart: unless-stopped
    tmpfs:
      - /tmp
      - /opt/aprsc/logs:mode=0777
    security_opt:
      - no-new-privileges:true